---
tailscale_deploy_access_user: ansible-deploy
tailscale_deploy_access_native_key_fingerprint: SHA256:UKIt1zHVexMpz9we72AErUd+DBrQh4cyoGa1gqOGPmA
tailscale_deploy_access_sshd_dropin: /etc/ssh/sshd_config.d/70-home-lab-native-deploy.conf
tailscale_deploy_access_sudoers_path: /etc/sudoers.d/ansible-deploy
