---
- name: Reload hardware rules
  ansible.builtin.command:
    argv:
      - /usr/bin/udevadm
      - control
      - --reload-rules
  changed_when: true
  listen: Reload hardware rules

- name: Trigger hardware rules
  ansible.builtin.command:
    argv:
      - /usr/bin/udevadm
      - trigger
  changed_when: true
  listen: Reload hardware rules

- name: Apply Wolf sysctls
  ansible.builtin.command:
    argv:
      - /usr/bin/sysctl
      - --system
  changed_when: true
  listen: Apply Wolf sysctls


- name: Rebuild Arch initramfs
  ansible.builtin.command:
    argv:
      - /usr/bin/mkinitcpio
      - -P
  changed_when: true
  listen: Rebuild Arch initramfs
