---
all:
  children:
    docker_host:
      hosts:
        docker-host-local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python
          lifecycle_contract_host: debian
          lifecycle_profile: production
