x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:v8.0.17@sha256:3badde1bcc2eab6bec729fca20e9953981574e34c0389bd5c810b20f955bf0b8
    container_name: cli-proxy-api
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 127.0.0.1:8317:8317
    volumes:
      - type: bind
        source: /etc/docker-compose/credentials/cli-proxy-api-config.yaml
        target: /CLIProxyAPI/config.yaml
        read_only: true
      - type: bind
        source: /srv/home-lab-state/cli-proxy-api/auths
        target: /root/.cli-proxy-api
    networks:
      - proxy
