x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:v7.3.15@sha256:86032129fa65496428752ec6e5c7480f07fde137160b728cd850cc65e9eaa391
    container_name: cli-proxy-api
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 127.0.0.1:8317:8317
    volumes:
      - type: bind
        source: /etc/docker-compose/credentials/cli-proxy-api-config.yaml
        target: /CLIProxyAPI/config.yaml
        read_only: true
      - type: bind
        source: /srv/home-lab-state/cli-proxy-api/auths
        target: /root/.cli-proxy-api
    networks:
      - proxy
