x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable@sha256:ff82c125c9b79b2e9443de2b0eaec40c904edb03291680d408cccd57c1d59c76
    container_name: wolf
    restart: unless-stopped
    logging: *default-logging
    network_mode: host
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'timeout 5 wget -qO- http://127.0.0.1:47989/serverinfo | grep -q ''status_code="200"''',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      TZ: $TZ
      LIBVA_DRIVER_NAME: radeonsi
      WOLF_RENDER_NODE: /dev/dri/renderD128
      WOLF_DEFAULT_RUN_UID: 1000
      WOLF_DEFAULT_RUN_GID: 1000
    volumes:
      - ${GAMES_PATH}/wolf:/etc/wolf
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev:/dev:rw
      - /run/udev:/run/udev:rw
    tmpfs:
      - /run/user/wolf
    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
      - /dev/uhid:/dev/uhid
    device_cgroup_rules:
      - "c 13:* rmw"
