x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  omada:
    image: mbentley/omada-controller:6.2@sha256:d281c115461bd5969e6e1864483e7bf57ca966bddde69d6a3b9a770f3289e273
    container_name: omada
    restart: always
    logging: *default-logging
    # Recommended for easier device discovery
    network_mode: host
    environment:
      TZ: $TZ
    volumes:
      - type: bind
        source: /srv/home-lab-state/omada-data/data
        target: /opt/tplink/EAPController/data
      - type: bind
        source: /srv/home-lab-state/omada-data/logs
        target: /opt/tplink/EAPController/logs

  ddns-updater:
    image: ghcr.io/qdm12/ddns-updater:v2.10.0@sha256:3e2aa558946b5a293def4d73008fa4651c072b2c12932cecd02126fb23979831
    container_name: ddns-updater
    restart: always
    logging: *default-logging
    volumes:
      - /srv/home-lab-state/ddns-updater-data:/updater/data
    environment:
      TZ: $TZ
      RESOLVER_ADDRESS: $RESOLVER_ADDRESS
      # See: https://pkg.go.dev/time#ParseDuration
      PERIOD: 5m
    networks:
      - proxy

  caddy:
    image: caddy:2.11.4@sha256:844f60b64e4724a5aa8245e019dace0d3f199f7433ce6c57676cb30a920dbad9
    container_name: caddy
    restart: always
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      TZ: $TZ
      ROUTE_53_ACCESS_KEY: $ROUTE_53_ACCESS_KEY
      ROUTE_53_SECRET: $ROUTE_53_SECRET
      ROUTE_53_ZONE_ID: $ROUTE_53_ZONE_ID
    volumes:
      - /srv/home-lab-state/caddy-data:/data/caddy
      - ./data/Caddyfile:/etc/caddy/Caddyfile
    networks:
      proxy:
        # Must match Home Assistant's trusted_proxies entry.
        ipv4_address: 172.23.0.250

networks:
  infra:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/16"
  proxy:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"
