#!/usr/bin/env python3
"""Saved, separately confirmed PVE controller capability installation (not acceptance)."""
import argparse
import base64
import datetime as dt
import hashlib
import json
import os
import re
from pathlib import Path
import shlex
import stat
import subprocess
import tempfile

from protected_execution import acquire_transfer_lock

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / '.local/proxmox-controller-observer-capability'
HOST = ROOT / 'infrastructure/proxmox-access/host/proxmox-controller-capability-transaction.py'
BASE = '/usr/local/libexec/home-lab/'
RULE = ('ansible-plan ALL=(root) NOPASSWD: ' + BASE + 'proxmox-observer observe, ' + BASE +
        'proxmox-package-candidate-observer observe proxmox, ' + BASE + 'proxmox-controller-observer observe\n')
FINGERPRINT = 'SHA256:uaxG9uESfphESCqWx3ialKjK0doHnVcFoUIGWMGcaYQ'
FORMAT = 'home-lab-proxmox-controller-observer-capability-v1'


def require_vfio_coordination():
    raise ValueError('installation blocked: VFIO queued-reboot ownership protocol is unqualified')


def canonical(value):
    return (json.dumps(value, sort_keys=True, separators=(',', ':')) + '\n').encode()


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def read(path, mode, private=False):
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1 or stat.S_IMODE(info.st_mode) != mode or info.st_size > 12 * 1024 * 1024 or (private and info.st_uid != os.getuid()):
            raise ValueError('capability input metadata differs')
        raw = b''
        while len(raw) <= info.st_size:
            block = os.read(fd, min(65536, info.st_size + 1 - len(raw)))
            if not block:
                break
            raw += block
        after = os.fstat(fd); named = os.stat(path, follow_symlinks=False)
        fields = ('st_dev', 'st_ino', 'st_mode', 'st_uid', 'st_gid', 'st_nlink', 'st_size', 'st_mtime_ns', 'st_ctime_ns')
        if len(raw) != info.st_size or any(getattr(info, f) != getattr(after, f) or getattr(info, f) != getattr(named, f) for f in fields):
            raise ValueError('capability input changed')
        return raw
    finally:
        os.close(fd)


def private(path):
    raw = read(path, 0o600, True); value = json.loads(raw)
    if canonical(value) != raw:
        raise ValueError('capability input not canonical')
    return value, raw


def git(*args):
    return subprocess.check_output(('git', *args), cwd=ROOT, text=True).strip()


def clean_commit():
    commit = git('rev-parse', 'HEAD')
    if commit != git('rev-parse', 'origin/main') or git('status', '--porcelain=v1', '--untracked-files=all'):
        raise ValueError('capability requires clean pushed reviewed HEAD')
    return commit


def ssh():
    path = Path(os.environ.get('HOME_LAB_PROXMOX_PRODUCTION_KNOWN_HOSTS', ''))
    if not path.is_absolute():
        raise ValueError('dedicated strict known-hosts required')
    read(path, 0o600, True)
    result = subprocess.run(('ssh-keygen', '-lf', str(path)), capture_output=True, text=True)
    lines = result.stdout.splitlines()
    if result.returncode or result.stderr or len(lines) != 1 or len(lines[0].split()) < 2 or lines[0].split()[1] != FINGERPRINT:
        raise ValueError('Proxmox known-host identity differs')
    return ('ssh', '-F', '/dev/null', '-T', '-o', 'BatchMode=yes', '-o', 'StrictHostKeyChecking=yes',
            '-o', 'UserKnownHostsFile=' + str(path), '-o', 'GlobalKnownHostsFile=/dev/null',
            '-o', 'HostKeyAlgorithms=ssh-ed25519', '-o', 'UpdateHostKeys=no', '-o', 'IdentitiesOnly=yes', '-o', 'RequestTTY=no',
            '-o', 'ClearAllForwardings=yes', '-o', 'PermitLocalCommand=no', 'proxmox@proxmox')


def consumer_gate():
    # These are independently owned consumers. Their integration cannot be
    # waived by an installer flag or a documentation-only qualification note.
    for name in ('maintenance-read-only-observer', 'package-candidate-observer'):
        source = (ROOT / 'infrastructure/maintenance/host' / name).read_text()
        if '"/var/lib/home-lab/reconciliation/apply.lock"' not in source:
            raise ValueError('installation blocked: retained apply.lock consumer migration missing: ' + name)


def sources(artifact):
    # Do not trust a supplied manifest as source provenance: rebuild and compare
    # every installed generated byte using the reviewed clean source revision.
    with tempfile.TemporaryDirectory(prefix='pve-capability-build-') as temp:
        generated = Path(temp) / 'artifact'
        result = subprocess.run(('node', str(ROOT / 'scripts/controller/build-proxmox-ansible-observer.js'),
                                 '--output-dir', str(generated)), cwd=ROOT, capture_output=True)
        if result.returncode or result.stderr:
            raise ValueError('capability source build failed')
        files = {}
        for name in ('proxmox-observer', 'proxmox-protected-collector', 'proxmox-controller-observer', 'proxmox-package-candidate-observer'):
            raw = read(artifact / name, 0o755)
            if raw != read(generated / name, 0o755):
                raise ValueError('artifact/source bytes differ')
            files[BASE + name] = base64.b64encode(raw).decode()
        if read(artifact / 'manifest.json', 0o644) != read(generated / 'manifest.json', 0o644):
            raise ValueError('artifact/source manifest differs')
    for name in ('proxmox-ansible-plan-transport', 'proxmox-ansible-deploy-activator'):
        files[BASE + name] = base64.b64encode(read(ROOT / 'infrastructure/proxmox-access/host' / name, 0o755)).decode()
    contract = subprocess.run(('node', '-e', "const fs=require('fs'),y=require('js-yaml');process.stdout.write(y.load(fs.readFileSync(process.argv[1],'utf8')).proxmox.access.service_accounts.find(x=>x.name==='ansible-plan').sudo.rule)", str(ROOT / 'infrastructure/contract/home-lab.yml')), capture_output=True)
    # Resolve the contract structurally below; no independent sudo policy input.
    if contract.returncode or contract.stdout.decode() + '\n' != RULE:
        raise ValueError('contract sudo authority differs')
    files['/etc/sudoers.d/ansible-plan'] = base64.b64encode(RULE.encode()).decode()
    return files


def bindings():
    paths = ('infrastructure/contract/home-lab.yml', 'infrastructure/contract/schema.json',
             'ansible/inventory/proxmox-production.yml', 'scripts/controller/proxmox-controller-observer-capability.py',
             'ansible/inventory/production.yml',
             'infrastructure/proxmox-access/host/proxmox-controller-capability-transaction.py')
    return {p: sha((ROOT / p).read_bytes()) for p in paths}


# Same public historical attribution catalog emitted by access-evidence v1.
# Recognizing a receipt record grants no conventional SSH/key authority.
ACCESS_ATTRIBUTIONS = {
    'SHA256:Je+jcqxxdCTlcMc8sZToiF3oZrLIJ+N6mxNhiosUIXw': 'current-proxmox-root-id-rsa',
    'SHA256:xnvOo0mjS/Ghwrbf8JovxNp51qFXQncLO4ygGvZPR7w': 'personal-laptop',
    'SHA256:6RaXU5sJ5bREB69ozsxdAFWVhYvCm9jlPAu7rSOx+dU': 'iphone-termius',
    'SHA256:UKIt1zHVexMpz9we72AErUd+DBrQh4cyoGa1gqOGPmA': 'work-laptop',
    'SHA256:/qSECkXxkpCIjTkBwa8XZZdRW2/seScon5uAKGlLC80': 'obsolete-proxmox-root-identity',
    'SHA256:SNH3GBfBBvbkycl78DbrIjbaC0rJxkvue+KF9qhpXrs': 'obsolete-proxmox-root-identity',
}


def validate_access(value, raw, commit, contract_sha256, inventory_sha256, now):
    def exact(item, fields):
        if not isinstance(item, dict) or set(item) != set(fields.split()):
            raise ValueError('access evidence schema differs')

    def hex64(item):
        return isinstance(item, str) and re.fullmatch(r'[0-9a-f]{64}', item) is not None

    def timestamp(item):
        if not isinstance(item, str) or re.fullmatch(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z', item) is None:
            raise ValueError('access evidence UTC timestamp differs')
        return dt.datetime.strptime(item, '%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=dt.timezone.utc)

    exact(value, 'format draft_sha256 commit contract_sha256 inventory_sha256 host_key_fingerprint created_at expires_at proofs console_attested_at')
    if len(raw) > 262144 or raw != canonical(value):
        raise ValueError('access evidence encoding or size differs')
    if (value['format'] != 'home-lab-proxmox-access-evidence-v1' or value['commit'] != commit or
            value['contract_sha256'] != contract_sha256 or value['inventory_sha256'] != inventory_sha256 or
            value['host_key_fingerprint'] != FINGERPRINT or not hex64(value['draft_sha256'])):
        raise ValueError('access evidence source/host binding differs')
    created, expires, attested = (timestamp(value[k]) for k in ('created_at', 'expires_at', 'console_attested_at'))
    if not created <= attested <= now <= expires or expires - created != dt.timedelta(minutes=30):
        raise ValueError('access evidence freshness differs')
    proofs = value['proofs']
    exact(proofs, 'strict_host_key plan_observer firewall_transport deploy_transport human_session tailnet_policy root_keys console')
    if proofs['strict_host_key'] is not True:
        raise ValueError('strict host-key proof missing')
    for name, hash_field in (('plan_observer', 'observation_sha256'), ('firewall_transport', 'inspect_sha256'),
                             ('deploy_transport', 'marker_plan_sha256')):
        item = proofs[name]
        exact(item, 'positive injection_rejected ' + hash_field)
        if item['positive'] is not True or item['injection_rejected'] is not True or not hex64(item[hash_field]):
            raise ValueError('access evidence positive/negative transport proof differs')
    exact(proofs['human_session'], 'positive')
    exact(proofs['console'], 'attested method')
    if (proofs['human_session']['positive'] is not True or proofs['console']['attested'] is not True or
            proofs['console']['method'] != 'physical-console-bootstrap-install-and-verify'):
        raise ValueError('independent human/console proof differs')
    tailnet = proofs['tailnet_policy']
    exact(tailnet, 'tests_present live_plan_noop expected_retirement_drift controller_plan_stdout_sha256')
    # Retirement drift exceptions belong to retirement, not capability admission.
    if (tailnet['tests_present'] is not True or tailnet['live_plan_noop'] is not True or
            tailnet['expected_retirement_drift'] is not False or not hex64(tailnet['controller_plan_stdout_sha256'])):
        raise ValueError('access evidence no-op tailnet proof differs')
    keys = proofs['root_keys']
    exact(keys, 'records attributed attributed_count total_count unresolved complete')
    if (keys['attributed'] != ACCESS_ATTRIBUTIONS or keys['unresolved'] != [] or keys['complete'] is not True or
            not isinstance(keys['records'], list) or len(keys['records']) > len(ACCESS_ATTRIBUTIONS)):
        raise ValueError('access evidence root-key catalog differs')
    fingerprints = []
    for record in keys['records']:
        exact(record, 'bits fingerprint comment type')
        if (type(record['bits']) is not int or not 256 <= record['bits'] <= 16384 or
                not isinstance(record['fingerprint'], str) or record['fingerprint'] not in ACCESS_ATTRIBUTIONS or
                not isinstance(record['comment'], str) or len(record['comment']) > 1024 or record['type'] not in ('RSA', 'ED25519')):
            raise ValueError('access evidence root-key record differs')
        fingerprints.append(record['fingerprint'])
    if len(set(fingerprints)) != len(fingerprints) or any(type(keys[k]) is not int or keys[k] != len(fingerprints)
                                                        for k in ('attributed_count', 'total_count')):
        raise ValueError('access evidence root-key counts differ')


def admission(access_path, backup_path, commit, expected_bindings):
    access, access_raw = private(access_path); backup, backup_raw = private(backup_path)
    now = dt.datetime.now(dt.timezone.utc)
    # Receipt v1 binds the producer's combined inventory, independently of the
    # capability plan's additional Proxmox-specific inventory binding.
    validate_access(access, access_raw, commit, expected_bindings['infrastructure/contract/home-lab.yml'],
                    expected_bindings['ansible/inventory/production.yml'], now)
    if not isinstance(backup, dict) or not isinstance(backup.get('evidence'), dict):
        raise ValueError('independent backup prerequisites missing')
    evidence = backup['evidence']
    if any(type(evidence.get(k)) is not int for k in ('accepted_mtime_epoch', 'pending_records', 'proton_copy_records')) or any(
            not isinstance(evidence.get(k), dict) for k in ('local_service', 'proton_service')):
        raise ValueError('independent backup prerequisite types differ')
    age = now.timestamp() - evidence['accepted_mtime_epoch']
    if backup.get('format') != 'home-lab-proxmox-reboot-backup-attestation-v1' or backup.get('commit') != commit or backup.get('authorized') is not False or backup.get('automatic_reboot') is not False or evidence.get('pending_records') != 0 or evidence.get('proton_copy_records', 0) < 1 or not 0 <= age <= 86400 or any(evidence.get(k, {}).get('result') != 'success' for k in ('local_service', 'proton_service')):
        raise ValueError('fresh retained backup prerequisite missing')
    return {'access_sha256': sha(access_raw), 'backup_sha256': sha(backup_raw)}


def remote(payload, commit, expected_bindings, transaction):
    transaction_path = 'infrastructure/proxmox-access/host/proxmox-controller-capability-transaction.py'
    if (clean_commit() != commit or bindings() != expected_bindings or
            sha(transaction) != expected_bindings.get(transaction_path) or
            read(HOST, 0o644) != transaction):
        raise ValueError('approved capability source changed before remote phase')
    # Never replace approved identities or reread executable bytes at dispatch.
    payload = {**payload, 'commit': commit, 'bindings': dict(expected_bindings)}
    result = subprocess.run((*ssh(), 'sudo -n -- /usr/bin/python3 -c ' + shlex.quote(transaction.decode('utf-8'))),
                            input=canonical(payload), capture_output=True, timeout=600)
    if result.returncode or result.stderr:
        raise ValueError('capability transaction ambiguous or failed; retain owner, inspect and separately approve exact rollback')
    value = json.loads(result.stdout)
    if canonical(value) != result.stdout:
        raise ValueError('capability receipt differs')
    return value


def save(value):
    OUTPUT.mkdir(parents=True, exist_ok=True, mode=0o700)
    info = OUTPUT.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) != 0o700:
        raise ValueError('capability plan directory differs')
    raw = canonical(value); digest = sha(raw); path = OUTPUT / (digest + '.json')
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, 'wb') as handle:
        handle.write(raw); handle.flush(); os.fsync(handle.fileno())
    return path, digest


def execute(args):
    if args.command in {'plan', 'apply'}:
        require_vfio_coordination()
        consumer_gate()
    commit = clean_commit(); expected_bindings = bindings()
    transaction = read(HOST, 0o644)
    files = sources(args.artifact)
    prerequisites = admission(args.access, args.backup, commit, expected_bindings)
    lock_path = ROOT / '.local/locks/proxmox-controller-capability.lock'
    lock_path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    descriptor = acquire_transfer_lock(lock_path)
    try:
        if args.command == 'plan':
            before = remote({'operation': 'observe', 'files': files}, commit, expected_bindings, transaction)['before']
            now = dt.datetime.now(dt.timezone.utc)
            value = {'format': FORMAT, 'commit': commit, 'bindings': expected_bindings, 'files': files, 'before': before,
                     'prerequisites': prerequisites, 'created_at': now.isoformat(),
                     'expires_at': (now + dt.timedelta(minutes=30)).isoformat(), 'authorized': False,
                     'automatic_apply': False, 'host_key_fingerprint': FINGERPRINT}
            path, digest = save(value)
            return {'path': str(path), 'plan_sha256': digest, 'authorized': False}
        value, raw = private(args.plan); digest = sha(raw)
        if args.plan.name != digest + '.json' or value.get('format') != FORMAT or value.get('commit') != commit or value.get('bindings') != expected_bindings or value.get('files') != files or value.get('prerequisites') != prerequisites or value.get('host_key_fingerprint') != FINGERPRINT or value.get('authorized') is not False or value.get('automatic_apply') is not False:
            raise ValueError('saved capability bindings differ')
        created, expires = (dt.datetime.fromisoformat(value[k]) for k in ('created_at', 'expires_at'))
        if expires - created != dt.timedelta(minutes=30) or (args.command == 'apply' and not created <= dt.datetime.now(dt.timezone.utc) <= expires):
            raise ValueError('saved capability freshness differs')
        expected = args.command + '-proxmox-controller-observer-capability-' + digest
        if os.environ.get('PROXMOX_CONTROLLER_OBSERVER_CAPABILITY_CONFIRMED') != expected:
            raise ValueError('exact separate confirmation required: ' + expected)
        payload = {'operation': args.command, 'plan_sha256': digest, 'files': files, 'before': value['before']}
        result = remote(payload, commit, expected_bindings, transaction)
        if args.command == 'apply':
            if set(result) != {'status', 'observation'} or result['status'] != 'candidate':
                raise ValueError('candidate receipt differs; retained owner requires inspection')
            observed = canonical(result['observation'])
            audit = subprocess.run(('node', str(ROOT / 'scripts/controller/proxmox-ansible-audit.js'),
                                    '--artifact-dir', str(args.artifact.resolve()), '--observation', '-'),
                                   input=observed, capture_output=True, timeout=180)
            if audit.returncode or audit.stderr or json.loads(audit.stdout).get('parity') is not True:
                # No unapproved retry or optimistic release after audit failure.
                # Exact separately confirmed rollback remains available.
                raise ValueError('candidate parity audit failed; retained owner requires exact reviewed rollback')
            result = remote({**payload, 'operation': 'commit', 'observation_sha256': sha(observed)}, commit, expected_bindings, transaction)
        if result != ({'status': 'committed', 'live_acceptance': False} if args.command in {'apply', 'cleanup-committed'} else {'status': 'rolled-back'}):
            raise ValueError('capability result differs')
        return {**result, 'plan_sha256': digest}
    finally:
        os.close(descriptor)


def main():
    parser = argparse.ArgumentParser(); sub = parser.add_subparsers(dest='command', required=True)
    for name in ('plan', 'apply', 'rollback', 'cleanup-committed'):
        command = sub.add_parser(name)
        if name != 'plan':
            command.add_argument('plan', type=Path)
        command.add_argument('--artifact', type=Path, required=True)
        command.add_argument('--access', type=Path, required=True)
        command.add_argument('--backup', type=Path, required=True)
    print(json.dumps(execute(parser.parse_args()), sort_keys=True))


if __name__ == '__main__':
    main()
