---
- name: Reload NFS exports
  ansible.builtin.command:
    argv:
      - /usr/sbin/exportfs
      - -ra
  changed_when: true
  listen: Reload NFS exports

- name: Rebuild Proxmox initramfs for ZFS tuning
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-initramfs
      - -u
      - -k
      - all
  changed_when: true
  listen: Rebuild Proxmox initramfs
